routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
Route::group(['domain' => 'localhost'],function() {
    // Route::group(['middleware' => ['web', 'language']], function () {
    //     Route::get('/', 'HomeController@getData')->name('/');

    //     Route::get('properties', 'PropertyController@getData')->name('properties');

    //     Route::get('properties/search', [
    //         'uses' => 'HomeController@searchHome',
    //         'as' =>'search.home',
    //     ]);
    //     Route::get('/search', [
    //         'uses' => 'SearchTestController@index',
    //         'as' => 'search.test'
    //     ]);
    //     Route::get('property/{listUrl}', [
    //         'uses' => 'PropertyController@showPropertyDetail',
    //         'as' => 'property.show',
    //     ]);

    //     Route::get('agents', 'AgentController@getData')->name('agents');

    //     Route::get('franchise', 'FranchiseController@getData')->name('franchise');

    //     Route::get('albums', 'GaleryController@getGallery')->name('albums');

    //     Route::get('gallery/{id}', [
    //         'uses' => 'GalleryDetailController@getGalleryDetail',
    //         'as' => 'gallery.detail',
    //     ]);

    //     Route::get('contact', 'ContactController@getData')->name('contact');

    //     Route::get('news', 'NewsController@getData')->name('news');

    //     Route::get('about', 'AboutController@getData')->name('about');

    //     Route::get('news/{id}', 'NewsController@newsDetail')->name('news.detail');

    // // Route::get('{domain}')->middleware(['domain' => '{domain}.localhost'])->name('domain.url');
    // });
});
/**
 * The sub-domain
 */



Route::group(['domain' => '{subdomain}.lifeincube.com'], function()
{
    Route::group(['middleware' => ['web', 'language']], function () {
        Route::get('/', 'HomeController@getData')->name('/');

        // Route::get('properties', 'PropertyController@getData')->name('properties');

        // Route::get('properties/search', [
        //     'uses' => 'HomeController@searchHome',
        //     'as' =>'search.home',
        // ]);
        // Route::get('/search', [
        //     'uses' => 'SearchTestController@index',
        //     'as' => 'search.test'
        // ]);
        // Route::get('property/{listUrl}', [
        //     'uses' => 'PropertyController@showPropertyDetail',
        //     'as' => 'property.show',
        // ]);

        // Route::get('agents', 'AgentController@getData')->name('agents');

        // Route::get('franchise', 'FranchiseController@getData')->name('franchise');

        // Route::get('albums', 'GaleryController@getGallery')->name('albums');

        // Route::get('gallery/{id}', [
        //     'uses' => 'GalleryDetailController@getGalleryDetail',
        //     'as' => 'gallery.detail',
        // ]);

        // Route::get('contact', 'ContactController@getData')->name('contact');

        // Route::get('news', 'NewsController@getData')->name('news');

        // Route::get('about', 'AboutController@getData')->name('about');

        // Route::get('news/{id}', 'NewsController@newsDetail')->name('news.detail');

   });
});

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use GuzzleHttp\Exception\RequestException;
use Illuminate\Http\Request;
use GuzzleHttp\Client as GuzzleHttpClient;
use GuzzleHttp\Psr7;
use App\Http\Helpers\Api;
use Illuminate\Support\Facades\Session;

class NewsController extends Controller
{
    protected $api;
    protected $client;
    protected $uri;


    public function __construct(Api $api)
    {
        $this->api = $api;
        $this->client = new GuzzleHttpClient(['base_uri' => $this->api->getBaseUri(), 'verify' => false]);
        $this->uri = $this->api->getBaseUri();
    }

    public function index($domain)
    {
        return $domain;
    }

    public function getData()
    {
        try {
            $getClient = $this->client->get('webnews' . '?language=' . Session::get('language') . '&pageNumber=1&pageSize=5');
            $body = $getClient->getBody();
            $body = \GuzzleHttp\json_decode($body, false);
            $uri = $this->uri;

            if ($getClient->getStatusCode() == 200) {
                return view('news')
                    ->with(['body' => $body])
                    ->with(['uri' => $uri]);
            } else {
                return redirect()->back()
                    ->with('error', 'something is error with API');
            }
        } catch (RequestException $e) {
            echo Psr7\str($e->getRequest());
            if ($e->hasResponse()) {
                echo Psr7\str($e->getResponse());
            }
        }
    }


    public function newsDetail($id)
    {
        try {
            $getClient = $this->client->get('webnews/'.$id);
            $body = $getClient->getBody();
            $body = \GuzzleHttp\json_decode($body, false);
            $uri = $this->uri;

            if ($getClient->getStatusCode() == 200) {
                return view('news-detail')
                    ->with(['body' => $body])
                    ->with(['uri' => $uri]);
            } else {
                return redirect()->back()
                    ->with('error', 'something is error with API');
            }
        } catch (RequestException $e) {
            echo Psr7\str($e->getRequest());
            if ($e->hasResponse()) {
                echo Psr7\str($e->getResponse());
            }
        }
    }
}

resources/views/layout/footer.blade.php
<style>

    address {
        font-size: 12px;
    }

    address ul li {
        display: inline;
        list-style-type: none;
        color: white;
    }

</style>
{{-- <html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Footer</title>
    <link rel="stylesheet" href="{{ asset('assets/css/custom.css')}}" type="text/css">
</head>
<body> --}}
<footer id="page-footer">
    <div class="inner">
        <section id="footer-main">
            <div class="container-news">
                <div class="row">
                    <div class="col-md-6 col-sm-6" style="padding-left: 2px;margin-left: -20px;">
                        <article class="contact-us">
                            <br><br>
                            <object class="comp-logo">
                            </object>
                            <address>

                                <ul>

                                        <li style="float: left;margin-right: 20px;margin-bottom: 4%;"><?php echo substr($footer->data->compAddress, 0,23) ?><br><?php echo substr($footer->data->compAddress, 23,27) ?><br><?php echo mb_strimwidth($footer->data->compAddress, 50, 51)?><br>
                                        <i class="fa fa-phone"></i>&nbsp;&nbsp;&nbsp;<?php echo $footer->data->compPhone1 .
                                                    '<br>' . '<i class="fa fa-fax"></i>' . '&nbsp;&nbsp;' . $footer->data->compFax1 . '<br>' .
                                                    '<i class="fa fa-envelope"></i>' . '&nbsp;&nbsp;&nbsp;' . $footer->data->compEmail;?></li>
                                       <!--  <li style="float: left;"><i
                                                    class="fa fa-phone"></i>&nbsp;&nbsp;&nbsp;<?php echo $footer->data->compPhone1 .
                                                    '<br>' . '<i class="fa fa-fax"></i>' . '&nbsp;&nbsp;' . $footer->data->compFax1 . '<br>' .
                                                    '<i class="fa fa-envelope"></i>' . '&nbsp;&nbsp;&nbsp;' . $footer->data->compEmail;?>
                                        </li>
 -->
                                </ul>
                            </address>

                            <br><br><br>
                        </article>
                    </div>
                </div><!-- /.col-sm-3 -->
            </div><!-- /.row -->
        </section>
    </div><!-- /.container -->

    <section id="footer-thumbnails" class="footer-thumbnails"></section><!-- /#footer-thumbnails -->

</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99368247-1', 'auto');
  ga('send', 'pageview');

</script>

{{-- </body>
</html>

 --}}

resources/views/layout/header.blade.php
<div class="header-wrapper">
        <div class="header">
          <div class="container">
            <div class="header-inner">
              <div class="navigation-toggle toggle">
                <span></span>
                <span></span>
                <span></span>
              </div>
              <!-- /.header-toggle -->
              <div class="header-logo">
               
                  <img src="{{ asset('assets/img/logo_remax.jpg') }}" class="svg" alt="Home">
                
              </div>
              <!-- /.header-logo -->
              <div class="header-nav pull-right">
                <div class="primary-nav-wrapper">
                  <ul class="nav">
                    @if($header->data)
                        @foreach($header->data as $data)
                            <li class="nav-item " >
                              <a href="{{ $data->wbmnAPI }}" class="nav-link {{ Request::is($data->wbmnAPI) ? 'active' : '' }}">{{ $data->wbmlName }}</a>
                            </li>

                        @endforeach
                    @endif
                    @if($language->data)
                    @foreach($language->data as $lg)
                        <li class="nav-item" >
                            <a href="?language={{$lg->langCode }}" class="">
                                    @foreach($language->linked->langFileId as $linked)
                                        @if($lg->links->langFileId == $linked->id)
                                            <img style="width: 30px; height: 15px; margin: 22px 7px 0px 0px;" src="{{ 'https://www.remax.co.id/prodigy/papi/'.$linked->filePreview.'?size=30,32' }}" alt="" class="img-responsive">
                                        @endif
                                    @endforeach
                            </a>
                        </li>
                    @endforeach
                    @endif
            
                  </ul>
                </div>
                <!-- /.primary-nav-wrapper -->
              </div>
             
              <!-- /.header-toggle -->
             
              <!-- /.header-actions -->
            </div>
            <!-- /.header-inner -->
          </div>
          <!-- /.container -->
        </div>
        <!-- /.header -->
      </div>

resources/views/layout/layout.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link href="{{ asset('assets/assets/libraries/slick/slick.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/libraries/slick/slick-theme.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/css/trackpad-scroll-emulator.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/css/chartist.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/css/jquery.raty.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/fonts/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/css/nouislider.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/css/explorer-red.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/assets/css/style.css') }}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('assets/img/favicon.png') }}">
    <title>Remax</title>
  </head>
  <body class="">
   <div class="page-wrapper">
       @yield('header')
   
        @include('layout.header')

      
        
        @yield('content')

      

        @yield('footer')
         <div class="footer-wrapper">
        <div class="footer">
          <div class="footer-inner">
            <div class="container">
              <div class="row">
                <div class="col-lg-4">
                  <div class="widget">
                    <h3>
                      <img src="{{ asset('assets/assets/img/REMAX_mastrwordmark.png') }}" class="svg" alt="Home">
                    </h3>
                    <br>
                   
                </div>
              </div>
               </div>
               <div class="row">
              <div class="col-lg-4">
                    <p>
                      Remax Kantor 
                    </p>
                    <p>
                      081276473812 Ruko Syahidinandar 06
                    </p>
                    <p>
                      Palembang
                    </p>

                    <ul class="social">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-google"></i></a></li>
                    </ul>
              </div>
               </div>
                <!-- /.col-* -->
               
                <!-- /.col-* -->
               
                <!-- /.col-* -->
             
              <!-- /.row -->
            </div>
            <!-- /.container -->
          </div>
          <!-- /.footer-inner -->
        </div>
        <!-- /.footer -->
      </div>  
      </div>
      

    <!-- /.side-overlay -->

    <script src="http://maps.googleapis.com/maps/api/js?libraries=weather,geometry,visualization,places,drawing&key=AIzaSyDmXybAJzoPZ6hH-Jhv7QMCSGgQ6MY8WqY" type="text/javascript"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/jquery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/tether.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/chartist.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/google-map-richmarker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/google-map-infobox.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/google-map-markerclusterer.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/google-map.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/jquery.trackpad-scroll-emulator.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/jquery.inlinesvg.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/jquery.affix.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/jquery.scrollTo.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/libraries/slick/slick.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/nouislider.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/jquery.raty.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/wNumb.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/particles.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/explorer.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/assets/js/explorer-map-search.js') }}"></script>
    <script src="{{ asset('js/vue.min.js') }}"></script>
    <script src="{{ asset('js/vue-filter.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.7.0/vue-resource.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vuejs-paginator/2.0.0/vuejs-paginator.js"></script>
    <script src="{{ asset('js/axios.min.js') }}"></script>
    <script src="{{ asset('js/lodash.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pagination.js') }}"></script>
    
   @yield('script')
  </body>
</html>

resources/views/layout/master.blade.php
<html lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ asset('assets/fonts/font-awesome.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/bootstrap/css/bootstrap.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/owl.carousel.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/selectize.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('assets/css/logo-slider.css') }}" type="text/css">

    <title>@yield('title')</title>
</head>

<body class="page" id="page-top">

<div id="page-preloader">
    <div class="loader-ring"></div>
    <div class="loader-ring2"></div>
</div>

<div class="wrapper">

    <div id="header">@yield('header')</div>

    <div id="container_here">@yield('content')</div>

    <div id="footer">@yield('footer')</div>

</div>


<script type="text/javascript" src="{{ asset('assets/js/jquery-2.1.4.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/jquery-migrate-1.2.1.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/owl.carousel.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/retina-1.1.0.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/masonry.pkgd.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/selectize.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/waypoints.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/custom.js') }}"></script>
<script>
    jQuery(document).ready(function($){
        $("a").click(function(event){
            link = $(this).attr("href");
            $.ajax({
                        url: link,
                    })
                    .done(function(html){
                        $("#container_here").empty().append(html);
                    })
                    .fail(function(){
                        console.log("error");
                    })
                    .always(function(){
                        console.log("complete");
                    });
            return false;
        });
    });
</script>

<!--[if gt IE 8]>-->
<script type="text/javascript" src="{{ asset('assets/js/ie.js') }}"></script>
<!--[endif]-->
@yield('script')

</body>
</html>

resources/views/layout/modal_franchise.blade.php
    <div id="modal-inquiry" class="modal" tabindex="-1">
        <div id="form-inquiry">
<div class="modal-dialog">
            <form class="modal-content" @submit.prevent="validateBeforeSubmit">
                <div class="modal-header text-center" style="height:150px;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2>Own an Office</h2>
                <span>Unlimited Income Opportunities</span>
            </div>
                <div class="modal-body">
                    <div class="form-group" style="margin-bottom: 0px">
                        <div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('name')}">
                            Name : <input v-validate="'required|alpha'" :class="{'input': true, 'is-danger': errors.has('name')}" style="text-transform: capitalize;" v-model="inquiry.name" type="text" name="name">
                            <span v-show="errors.has('name')" class="text-danger">@{{ errors.first('name') }}></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('email')}">
                            Email : <input v-validate="'required|email'" style="text-transform: capitalize;" :class="{'input': true, 'is-danger': errors.has('email')}" v-model="inquiry.email" type="text" name="email">
                            <span v-show="errors.has('email')" class="text-danger">@{{ errors.first('email') }}></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('phone')}">
                            Phone : <input v-validate="'required|numeric'" :class="{'input': true, 'is-danger': errors.has('phone')}" style="text-transform: capitalize;" v-model="inquiry.phone" type="text" name="phone">
                            <span v-show="errors.has('phone')" class="text-danger">@{{ errors.first('phone') }}></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('email')}">
                            Message :
                            <textarea v-validate="" :class="{'input:': true, 'is-danger': errors.has('message')}" v-model="inquiry.message" style="width: 100%; height: 150px; margin-top: 10px;text-transform: capitalize;" name="message"></textarea>
                            <span v-show="errors.has('message')" class="text-danger">@{{ errors.first('message')}}</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer" style="padding: 10px;margin-top: 0px;">
                    <div class="form-group">
                        <button id="error-submit" type="submit" class="btn btn-block" @click="postInquiry">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        </div>



    </div>

resources/views/layout/modal_inquiry_agent.blade.php
{{-- <!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Modal error report</title>
	<style>
		.form-group{
			margin-bottom: 0px;
		}
	</style>
</head>
<body> --}}
	<div id="modal-inquiry" class="modal" tabindex="-1">
		<div id="form-inquiry">
<div class="modal-dialog">
			<form class="modal-content" @submit.prevent="validateBeforeSubmit">
				<div class="modal-header text-center" style="height:150px;">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h2>Become a Proud RE/MAX AGENT</h2>
					<span>Unlimited Income Opportunities</span>
				</div>
				<div class="modal-body">
					<div class="form-group" style="margin-bottom: 0px">
						<div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('name')}">
							Name : <input v-validate="'required|alpha'" :class="{'input': true, 'is-danger': errors.has('name')}" style="text-transform: capitalize;" v-model="inquiry.name" type="text" name="name">
							<span v-show="errors.has('name')" class="text-danger">@{{ errors.first('name') }}></span>
						</div>
					</div>
					<div class="form-group">
						<div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('email')}">
							Email : <input v-validate="'required|email'" :class="{'input': true, 'is-danger': errors.has('email')}" style="text-transform: capitalize;" v-model="inquiry.email" type="text" name="email">
							<span v-show="errors.has('email')" class="text-danger">@{{ errors.first('email') }}></span>
						</div>
					</div>
					<div class="form-group">
						<div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('phone')}">
							Phone : <input v-validate="'required|numeric'" :class="{'input': true, 'is-danger': errors.has('phone')}" style="text-transform: capitalize;" v-model="inquiry.phone" type="text" name="phone">
							<span v-show="errors.has('phone')" class="text-danger">@{{ errors.first('phone') }}></span>
						</div>
					</div>

					<div class="form-group">
						<div :class="{ 'control': true , 'input': true, 'is-danger': errors.has('message')}">
							Message :
							<textarea v-validate="" :class="{'input:': true, 'is-danger': errors.has('message')}" v-model="inquiry.message" style="width: 100%; height: 150px; margin-top: 10px;text-transform: capitalize;" name="message"></textarea>
							<span v-show="errors.has('message')" class="text-danger">@{{ errors.first('message')}}</span>
						</div>
					</div>
				</div>
				<div class="modal-footer" style="padding: 10px;margin-top: 0px;">
					<div class="form-group">
						<button id="error-submit" type="submit" class="btn btn-block" @click="postInquiry">Submit</button>
					</div>
				</div>
			</form>
		</div>
		</div>



	</div>

resources/views/layout/shareFacebook.blade.php
<div class="social-buttons">
    <a href="https://www.facebook.com/sharer/sharer.php?u={{ urlencode($url) }}"
       target="_blank">
       <i class="fa fa-facebook-official"></i>
    </a>
</div>